services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/development/Dockerfile
    depends_on:
      - postgres
    container_name: pokedex
    image: pokedex
    env_file:
      - .envs/.app
      - .envs/.postgres
      - .envs/.redis
    volumes:
      - .:/app
    command: scripts/start.sh

  celery-worker:
    container_name: celery-worker
    image: pokedex
    depends_on:
      - postgres
      - redis
    env_file:
      - .envs/.app
      - .envs/.postgres
      - .envs/.redis
    volumes:
      - .:/app
    command: scripts/start_worker.sh

  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres

  redis:
    image: redis:8-alpine
    container_name: pokedex-redis

  flower:
    image: mher/flower
    container_name: pokedex-flower
    env_file:
      - .envs/.redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/templates/default.conf.template
      - ./static/:/static/
      - ./media/:/media/
    env_file:
      - .envs/.nginx
    depends_on:
      - app
    ports:
      - 80:80
