# Generated by Django 5.2.1 on 2025-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
