# Generated by Django 5.2.1 on 2025-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0003_alter_pokemon_options_alter_type_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
