# Generated by Django 5.2.1 on 2025-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0004_alter_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("is_main_series", models.BooleanField(default=False)),
            ],
        ),
    ]
