# Generated by Django 5.2.1 on 2025-05-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0005_ability"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="front_sprite",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.ability",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "unique_together": {("pokemon", "ability"), ("pokemon", "slot")},
            },
        ),
    ]
