# Generated by Django 5.2.1 on 2025-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemons",
            "0006_pokemon_front_sprite_pokemon_height_pokemon_weight_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ability",
            options={"ordering": ["name"], "verbose_name_plural": "abilities"},
        ),
    ]
