# Generated by Django 5.2.1 on 2025-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0007_alter_ability_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="abilities",
            field=models.ManyToManyField(
                related_name="pokemons",
                through="pokemons.PokemonAbility",
                to="pokemons.ability",
            ),
        ),
    ]
